title: Analytics Portfolio
author: Jennifer Cooper
email: alaxiajune@gmail.com
description: All the things data can do...

# social links
github_username: AlaxiaJune # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
